"""add document text extraction fields

Revision ID: d0deb7eb24a7
Revises: 1ade72a8653a
Create Date: 2026-09-25 22:17:33.185683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0deb7eb24a7'
down_revision: Union[str, Sequence[str], None] = '1ade72a8653a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('processing_error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
